[BBB-50] SNS 글쓰기 페이지 구현
BangBangBwa/Frontend pull request #13
Opened 2024-11-07 11:01 UTC by chaeyun-sim

### 🔍️ 개요

> 작업 목적을 설명해주세요.

- 글쓰기 페이지 구현

<br></br>

### 🔖 작업 내용

> 주요 변경 사항에 대해 설명해주세요.

- UI 구현
- Toast UI 에디터를 활용하여 에디터 구현 및 커스터마이징
- 사용자 선택을 위한 드롭다운 구현
- 방송인 등업 페이지로 이동할 모달 구현

<br></br>

### 💬 리뷰어에게

> 리뷰가 필요한 사항 등

- api는 추후 작업할 예정입니다.
- 에디터는 markdown 형식이 아닌 wysiwyg 형식으로만 고정해두었고, api로 넘길 때는 HTML 추출해서 전달하려고 합니다.
- 수정될 부분 있으면 말씀해주세요!

<br></br>

### 📝 참고 사항

> 필요한 경우 피그마나 GIF 등 첨부

<img width="2240" alt="스크린샷 2024-11-07 오후 7 57 16" src="https://github.com/user-attachments/assets/90f74092-999e-4547-b218-5362f40faf19">
<img width="2240" alt="스크린샷 2024-11-07 오후 7 58 00" src="https://github.com/user-attachments/assets/ca9e07be-2cf3-4e73-8adb-454da2c82a97">

<br></br>

2024-11-09 08:21 UTC, yujinyny requested changes

2024-11-09 08:21 UTC, yujinyny commented on src/components/common/Header.tsx
> +          className={css({ width: 380, height: 240 })}
width, height 에서 className props 수정하신 이유가 궁금합니다!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +                <button
컴포넌트를 분리하는 것이 좋겠습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/components/VisibilityOption.tsx
> +const VisibilityOption = ({
component/common/CheckBox.tsx 컴포넌트를 사용하시면 될 거 같습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +            tabList={[
현재 파일이 코드 양이 다소 길어서 contant로 따로 분리해서 관리하면 가독성이 더 좋을거 같습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +          <div style={{ padding: '0 16px' }}>
`!isPublic`일 시 people 목록 영역을 안보이게 하는게 어떨까요?

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +  const handleClickDropdown = (person: string) => {
handleAddPublicPerson, handleDeletePublicPerson 등으로 함수명을 설정해서 두 함수가 반대 역할을 한다는 의미를 드러내면 코드를 파악하기 더 수월해질거 같습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/components/SelectPeopleDropdown.tsx
> +    const filtered = peoples.filter((p) => p.startsWith(keyword));
include가 아니라 startsWith인가요?

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +            <SelectPeopleDropdown
혹시 이 부분을 왜 Dropdown으로 구현하신걸까요?!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +    setIsDropdownOpen(!!searchText);
searchText가 없으면 드롭다운이 닫히는 것이 아닌, 전체 팔로우 리스트가 보여야 한다고 생각이 듭니다!

2024-11-09 08:21 UTC, yujinyny commented on src/components/SelectPeopleDropdown.tsx
> +      {isDropdownOpen && data.length > 0 && (
해당 컴포넌트를 드롭다운으로 구현하지 않아도 된다면 `isDropdownOpen` 상태를 모두 제거하고, `data.length > 0 && `으로 처리해도 될 거 같습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +      privateMembers: [],
privateMembers를 꼭 전달해야 하는건지 백엔드팀에게 요청해봐도 좋을 거 같습니다!

2024-11-09 08:21 UTC, yujinyny commented on src/components/SelectPeopleDropdown.tsx
> +    const filtered = peoples.filter((p) => p.startsWith(keyword));
현재 코드에서는 peoples(원본 데이터)를 기준으로 필터링을 하여, 아래 handleClickItem을 통해 선택된 아이템은 필터링되지 않을거 같습니다...

`peoples.fileter(선택되지 않은 사람).filter((p) => p.startsWith(keyword))` 이렇게 해야 되겠네요... 뭔가 좋은 방법이 있을텐데 그림이 잘 그려지지 않네요ㅠㅠ

2024-11-09 08:21 UTC, yujinyny commented on src/components/SelectPeopleDropdown.tsx
> +    const filtered = peoples.filter((p) => p.startsWith(keyword));
위와 같이 한다면 최상위(pages/post.tsx)에서 `publicMembers`, `privateMembers` 상태를 따로 두고 `handleAddPublicMember`, `handleDeletePublicMember` 두 함수에서 두 상태를 관리하면 어떨까요!

2024-11-09 08:21 UTC, yujinyny commented on src/pages/post.tsx
> +          onClose={() => setSelectedTab('1')}
현재 코드상으로는 탭2를 선택시 모달만 열릴 뿐 탭2로 seletedTab 값이 변하지 않아서 `setIsModalOpen(false)`로 둬도 될 거 같습니다!

2024-11-09 08:37 UTC, chaeyun-sim commented on src/components/common/Header.tsx
> +          className={css({ width: 380, height: 240 })}
panda에서 컴포넌트 내 className css는 동적 스타일 할당이 안되어서 Modal에 직접 className을 작성해서 넣는 방법을 선택했습니다!
그러고보니 props로 받아서 style에 넣으면 될 걸 그랬네요..ㅎㅎㅎ...

2024-11-09 08:39 UTC, chaeyun-sim commented on src/pages/post.tsx
> +          <div style={{ padding: '0 16px' }}>
저도 이 부분 연정님께 건의했었는데 기획안에서는 비공개에서도 보이는 걸로 되어있다고 하셨습니다 ㅜㅜ

2024-11-09 08:40 UTC, chaeyun-sim commented on src/pages/post.tsx
> +            <SelectPeopleDropdown
앗 질문이 어떤 의미인가요..??

2024-11-09 09:09 UTC, chaeyun-sim commented on src/components/SelectPeopleDropdown.tsx
> +      {isDropdownOpen && data.length > 0 && (
이 부분 수정하면서

인풋 클릭 시(검색어 없음) -> 전체 데이터 표시
검색어 입력 시 -> 일치하는 부분만 하이라이트

이렇게 바꿨습니다!!

2024-11-09 09:09 UTC, chaeyun-sim commented on src/pages/post.tsx
> +      privateMembers: [],
로그인/회원가입 API 반영된 후에 테스트하면서 요청해보려고 합니닷

2024-11-12 11:14 UTC, yujinyny approved these changes
고생하셨습니다!

2024-11-12 11:25 UTC, merged