[BBB-40] 홍보 페이지 구현
BangBangBwa/Frontend pull request #6
Opened 2024-10-31 08:25 UTC by chaeyun-sim

### 🔍️ 개요

> 작업 목적을 설명해주세요.
- 홍보 페이지 (메인 페이지) 구현

<br></br>

### 🔖 작업 내용

> 주요 변경 사항에 대해 설명해주세요.
- 홍보 페이지 구현
- 배너 API 및 스트리머 API 연동
- panda.config에 fontWeight 관련 theme 추가
- main-light0 컬러 추가
- publicInstance, authInstance 구현 및 수정

<br></br>

### 💬 리뷰어에게

> 리뷰가 필요한 사항 등
- axios instance를 publicInstance(토큰 없음), authInstance(토큰 필수)으로 분리하였고, 아직 토큰이 적용된 api가 없어서 일단 모두 publicInstance으로 해두었습니다.
- api에서 빠진 데이터가 추가되면 머지할 생각입니다.

<br></br>

### 📝 참고 사항

> 필요한 경우 피그마나 GIF 등 첨부
<img width="1232" alt="스크린샷 2024-10-31 오후 5 06 08" src="https://github.com/user-attachments/assets/17c67046-a396-4065-89cb-4d6eb80174b4">

<br></br>

2024-10-31 11:55 UTC, yujinyny requested changes
채윤님 배포 테스트 하면서 develop에 추가한 코드랑 충돌이 생겨서 제가 수정해서 다시 올려놓았습니다!

2024-10-31 11:55 UTC, yujinyny commented on src/components/Banner.tsx
> +      {data?.map((item) => (
data가 없으면 swiper가 어떻게 보이게 되나요?

2024-10-31 11:55 UTC, yujinyny commented on src/components/MainPage/StreamerCard.tsx
> +          <h2 className={styles.name}>{name}</h2>
h2 태그 지정하기엔 우선순위가 높지 않은 내용같아서 p나 span 태그를 사용하면 어떨까요?

2024-10-31 11:55 UTC, yujinyny commented on src/components/MainPage/StreamerCard.tsx
> +    width: '220px',
해당 부분은 layout width가 940px 기준일 때만 적용되기 때문에,
Card에 width를 fix하지 않고 상위 컴포넌트(cards_wrapper)에서 grid를 적용해주는게 맞을거 같습니다!

2024-10-31 11:55 UTC, yujinyny commented on src/apis/auth.ts
> +        'Access-Control-Allow-Origin': '*',
publicInstance 생성 시 headers에 작성하지 않고 이 부분에 따로 작성하신 이유가 있을까요??

2024-10-31 11:57 UTC, chaeyun-sim commented on src/apis/auth.ts
> +        'Access-Control-Allow-Origin': '*',
옮겨두겠습니다!

2024-10-31 13:11 UTC, chaeyun-sim commented on src/components/MainPage/StreamerCard.tsx
> +    width: '220px',
cards_wrapper은 gridTemplateColumns으로 해뒀고, 스트리머카드는 maxWidth을 줬습니다.
이렇게 하면 될까요?

2024-10-31 13:19 UTC, yujinyny commented on src/components/MainPage/StreamerCard.tsx
> +    width: '220px',
넵!

2024-10-31 13:26 UTC, chaeyun-sim commented on src/components/MainPage/StreamerCard.tsx
> +    width: '220px',
@yujinyny 이 부분 수정했는데 말씀하신 것과 일치하는 지 한번 봐주세요..!

2024-10-31 13:27 UTC, yujinyny commented on src/components/MainPage/StreamerCard.tsx
> +    width: '220px',
넵 확인했습니다!

2024-10-31 13:33 UTC, chaeyun-sim commented on src/components/Banner.tsx
> +      {data?.map((item) => (
배너는 관리자가 직접 관리하는 부분이라서 배너가 없는 경우가 없다고 생각했었어요! 그래도 혹시 모르니까 피그마에 댓 남겨 두겠습니다ㅎㅎ

2024-11-02 07:26 UTC, yujinyny approved these changes
고생하셨습니다 🙇‍♀️

2024-11-02 07:27 UTC, merged